### ISSUE TITLE
`TableView`: use border for transient selections

### ISSUE THREAD

**Issue by rolyp** [explorable-viz/fluid#1084]
- [x] Remove `box-shadow` (shadow bleeds onto borders which should not be visible)
- NW corner of transient border overwritten by S and E borders of cell to NW
  - For initial config, set: 
    - [x] For all cells: `border-top` and `-left` to transparent and `border-bottom` and `-right` to none 
    - [x] `border-right` to transparent for cells in last column
    - [x] `border-bottom` to transparent for cells in last row
- [x] Transient highlighting (see Haofei notes below)
- [x] Rename `record_isDisplayable` to `record_isVisible`
- <s>`record_isDisplayable` to take `filter` into account</s> :see #858
- <s>Rethink “interior” (maybe background colour that alpha-blends with persistent highlighting?)</s> :x: tricky, leave for now

The `::before` and `::after` pseudo-elements might be helpful for restricting the scope of a `box-shadow`, but it may also be worth looking at other solutions (e.g. avoiding `box-shadow` entirely and perhaps using a transparent fill instead).

***
`MatrixView` transient selection highlighting is quite nice (since #1020), whereas `TableView` transient selection highlighting is not (by comparison). Moreover, having different default behaviours on similar visual outputs is probably unhelpful. We should be able to adopt a similar style for `TableView`, drawing borders on the “exterior” of selected regions and using the CSS `filter` attribute (or similar) to add drop shadows.

One subtlety about `TableView` is that by default we hide rows with only unselected columns. The question thus arises of whether two cells are considered “adjacent” in the N-S direction only when they are adjacent in the full table, or when they are visually adjacent because the rows that usually separate them are hidden. (I suggest the latter.) A similar question would arise in the E-W direction if we hid columns in the same way.

See also:
- #1020 
- #952

**Comment by hafniz** [comment]
This [post](https://stackoverflow.com/questions/4096390/table-border-color-in-css-with-border-collapse) mentions the order to render table cell borders when the `border-collapse` property of a table is set to `collapse`:

> if collapsing borders have the same style and width, but differ in color, then ... from most to least preferred: cell, row, row group, column, column group, table.
>
>if ... come from same type of element, such as two rows... then color is taken from borders that are the topmost and the leftmost.

i.e. the **south** border of the top cell has priority over the north border of the bottom cell, and the **east** border of the cell to the left has priority over the west border of the cell to the right. If both adjacent cells specify their borders, only the border that has priority will be rendered, even if its color is partially or fully transparent.

Therefore for border highlighting it is sufficient to consider only the south border and the east border of each cell, including the cells in the header row at the very top and those in the row-number column at the very left.

Drop-shadows can be achieved with the `box-shadow` property on table cells: 

```css
td {
    box-shadow:
        inset 0px 1px 1px rgba(0, 0, 255, 0.3),   /* top-down */
        inset 0 -1px 1px rgba(0, 0, 255, 0.3),    /* bottom-up */
        inset 1px 0 1px rgba(0, 0, 255, 0.3),     /* rightwards from the west border */
        inset -1px 0 1px rgba(0, 0, 255, 0.3);    /* leftwards from the east border */
}
```

as cell 1 in the screenshot below shows.

Cell 5 is rendered instead with outward (non-`inset`) shadows from adjacent cells, i.e. a downward shadow from cell 2, an upward shadow from cell 8, a rightward shadow from cell 4 and a leftward shadow from cell 6. However, it seems that some non-`inset` shadows have a lower z-index than, and will be blocked by, the cell backgrounds, whereas `inset` shadows are not affected. 

![image](https://github.com/user-attachments/assets/77b5e979-1419-4fa2-baf8-b30da3c71977)

So I think a rough sketch of the implementation would be: for the cells in the header row and cells in the row-number column, ask what its east and south borders need to be (transparent/blue(/lightblue for secondary selection?)); for cells containing actual data, ask the same questions, plus the additional questions of whether it needs an internal north/south/west/east shadow.

Alternatively, the required shadows can be computed at the same time when working out the required borders. If this information can be stored in some data structure and we can individually set the styles of the table cells by accessing the cells via indexing (instead of calling the same function on each cell), then it is probably better doing this way in terms of performance. I don't know how much complexity this will bring to the code base, though.

**Comment by rolyp** [comment]
@hafniz Sounds good. I would go for the simplest approach initially and only worry about performance if it becomes an issue.

**Comment by rolyp** [comment]
Hi @hafniz thanks for your excellent work on this. I've listed the remaining todo's in order of priority. The `box-shadow` problem seems least important -- perhaps we can come up with a different kind of transient highlighting rather than wasting time on a complex solution based on drop shadows. (Maybe a partially transparent fill would work better!)

The `filter` thing won't be hard so if you do spend any more time on this, the NW corner issue seems the most pressing. But you've worked hard and done an excellent job, so I'm also happy for you to leave things as they are. Speak Monday!

**Comment by hafniz** [comment]
Workaround for the corner issue (assuming `border-collapse: collapse`): 

- For all cells, set `border-top` and `border-left` to transparent (so that they take up the space between each pair of adjacent cells) and `border-bottom` and `border-right` to none. 
- Set `border-right` to transparent for the cells in the last column, and `border-bottom` to transparent for the cells in the last row.
- To highlight **top** border of a cell, toggle the **bottom** border of the cell **immediately above it**, regardless of visibility. 
- To highlight **bottom** border of a cell, toggle the **bottom** border of the cell **immediately above the next visible cell below it**. E.g. if cell h32 and cell h42 is hidden in between cell 5 and cell 8, then toggle the bottom border of cell h42 – see the code below.
- To highlight **left** border of a cell, toggle the **right** border of the cell **immediately to the left**.
- To highlight **right** border of a cell, toggle the **right** border of the cell itself.

This approach ensures that all four corners of a cell are covered by the highlight borders, assuming that columns are always visible and only rows can be hidden. If we were to implement #952 at some point then the logic for left and right borders would be akin to that for the top and bottom borders. 

![image](https://github.com/user-attachments/assets/70c42d17-7b76-4e1c-a6d3-5b4d864e2041)

```html
<!DOCTYPE html>
<html>

<head>
    <style>
        table {
            border-collapse: collapse;
            width: 50%;
            margin: 50px auto;
        }

        td {
            border-top: 1px solid yellow;
            border-left: 1px solid lightblue;
            background: lightgray;
        }

        .s3, .s6, .s9 {
            border-right: 1px solid green;
        }

        .s7, .s8, .s9 {
            border-bottom: 1px solid red;
        }

        .s22 {
            border-bottom: 1px solid purple;
        }

        .s4 {
            border-right: 1px solid purple;
        }

        .s5 {
            border-right: 1px solid purple;
        }

        .s42 {
            border-bottom: 1px solid purple;
        }

        .hidden {
            visibility: collapse;
        }
    </style>
</head>

<body>
    <table>
        <tr>
            <td class="s1">Cell 1</td>
            <td class="s2">Cell 2</td>
            <td class="s3">Cell 3</td>
        </tr>
        <tr class="hidden">
            <td>Cell h11</td>
            <td>Cell h12</td>
            <td>Cell h13</td>
        </tr>
        <tr class="hidden">
            <td>Cell h21</td>
            <td class="s22">Cell h22</td>
            <td>Cell h23</td>
        </tr>
        <tr>
            <td class="s4">Cell 4</td>
            <td class="s5">Cell 5</td>
            <td class="s6">Cell 6</td>
        </tr>
        <tr class="hidden">
            <td>Cell h31</td>
            <td>Cell h32</td>
            <td>Cell h33</td>
        </tr>
        <tr class="hidden">
            <td>Cell h41</td>
            <td class="s42">Cell h42</td>
            <td>Cell h43</td>
        </tr>
        <tr>
            <td class="s7">Cell 7</td>
            <td class="s8">Cell 8</td>
            <td class="s9">Cell 9</td>
        </tr>
    </table>
</body>

</html>
```
