### ISSUE TITLE
0.7.4 website layout and content, final version

### ISSUE THREAD

**Issue by rolyp** [explorable-viz/fluid#1168]
See also:
- explorable-viz/fluid#1490 
- explorable-viz/fluid#1179

Done/dropped:
- [x] Matrix convolution and moving average pages: add some padding before `p` (but not on `p + p`)
- [x] Lose `id=”data-pane”`?
- [x] `fa-solid fa-eye-slash` or similar ([FontAwesome 5](https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css)) for data pane toggle
- [x] Revisit `<a>` colours given new “purple” theme
- [x] `fa-solid fa-eye` when data pane visible
- [x] Fluid logo as local image
- [x] Header a bit cramped
- [x] `<ul>` on landing page (when hidden) causes grid container to be taller than expected 
- [x] Misc: `clickToggle` not working on new `<i>` icons (`data-pane-hidden` not initialised on `grid-container`)
- [x] Shared footer
- [x] More padding to header (similar to footer)
- [x] Change copyright declaration to “Fluid contributors”
- [x] Larger default font sizes
- [x] Revisit `highlight` style so it doesn’t look like `active-page` (try `<b>`)
- [x] Make it more obvious that `moving-average` is laggy if you happen to mouse over “Agriculture”
- [x] Tag 0.7.4 release
- [x] Merge `develop` to `release`
  - [x] Disable `deploy-npm` job for now

**Comment by rolyp** [comment]
@RaoOfPhysics You can add comments here if you like

**Comment by RaoOfPhysics** [comment]
The first impression is lovely. The font, colour scheme and layout is generally very pleasing to the eye. I have some comments, which will hopefully make the page stronger.

- Both Firefox and Chromium (on my rather old, 8GB-RAM Linux laptop) flash messages saying that the website is slowing down the browser, while the front-page example is loading. I wonder if there is something that can be done about this.
- Could we add more padding to the header so the content within it can breathe a little? Similar to the footer, which has lots of space above and below it and the text itself has a decent amount of vertical padding.
- Maybe consider changing the copyright declaration to “Fluid contributors”.
- Consider changing the default font size to slightly larger. Subjectively, it looks a bit small for me and I had to zoom in to 110% to read it comfortably.
- The use of the purple highlights is a little confusing. In the header and the “tabs” below “Overview”, it indicates the current location where one is, in relation to other links present on the page. However, within the body, it serves the purpose of drawing attention to specific bits of text. That said, it looks suspiciously like a link (even though the links are all underlined by default. I would suggest changing these to regular `<b>` tags (not `<strong>`! see [SO](https://stackoverflow.com/questions/271743/whats-the-difference-between-b-and-strong-i-and-em) and [mdn web docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong#b_vs._strong) for differences).
- The grey text in the left sidebar is distracting. It’s clear that it’s not under consideration because none of those columns get highlighted. Nevertheless, the text is present and the eye tries to parse it, but it is too light to read without straining. I don’t know what the solution is. Embolden the highlighted text, leave the other text with a normal weight? Give the unused text a slightly lighter weight while retaining the normal weight for the highlighted bits? That is, change the weights instead of changing the colour.
- I miss the old “toggle” icon. It was a bit clearer that something appears to the side. But no strong feelings about this!

**Comment by RaoOfPhysics** [comment]
[Contd.]

- If http://127.0.0.1:8080/convolution-wrapped/ is an extension of the Matrix Convolution example, should the relevant text at the top of the page be highlighted purple without being a hyperlink?
- http://127.0.0.1:8080/moving-average/ seems a bit slow, but I can’t figure out why. Hovering over the years takes ages to get registered.
- FAQ is lovely. Would be nice if we could use anchor tags for specific questions so we can link directly to them. Not much overwhelming content at the moment so not a major concern. Can always do things like [this](http://127.0.0.1:8080/faq#:~:text=Why%20do%20images%20take%20a%20while%20to%20load%3F) for now.

**Comment by rolyp** [comment]
Thanks @RaoOfPhysics, very useful comments – I’ll reply properly later (tied up until 4pm).

**Comment by rolyp** [comment]
Great feedback @RaoOfPhysics. I’m going to try to pick off the easy ones as part of this task and then upload the new website before I go away on holiday tomorrow. The remaining issues I’ve moved to explorable-viz/fluid#1490.

On a couple of your points:
- The `moving-average` example is super-slow if you accidentially mouse over the string “Agriculture” in the table. Unfortunately that’s very easy to do, and at the moment there’s no easy fix.
- Agreed re. `convolution-wrapped` and the “active page” highlighting – I’ve implemented that in a generic way (which is nice because the website author doesn’t need to think about it) but unfortunately the approach is based on the `href` text that appears in the `<a>` tag, and it doesn’t work here. Again no easy fix, but I’ll come back to it.

**Comment by rolyp** [comment]
@RaoOfPhysics Gah, GraphikLight doesn’t really support `bold` properly – it’s hardly distinguishable from regular font weight (I remember now that that is why I didn’t use it!). I’ve switched to `GraphikMedium`, which isn’t quite ideal as it has a noticably different spacing, but it’s more legible than GraphikLight `bold`. And I’ve removed the confusing highlight colour, so at least it no longer looks like a hyperlink.
