### ISSUE TITLE
Backward slicing over dependence graphs

### ISSUE THREAD

**Issue by rolyp** [explorable-viz/fluid#639]
Implement the algorithm in the paper.

**Comment by JosephBond** [comment]
Issues to sort before continuing:

- [x] Consolidate graph through Dict.purs
- [x] remove allocate from Graph typeclass
- [x] replace variable names in graph.purs with g (graph metavariable) where possible
- [x] replace lets with where in order to help with yarn tidy
- [x] do some eta-contraction in a few lambdas
- [x] rename e1 x e2 edges to alpha x beta
- [x] can remove unnecessary parens
- [x] set -> alphas
- [x] elem move to graph typeclass
- [x] inline some variables in bwd and fwd slicing
- [x] rename bwdSlice’ to bwdEdges
- [x] refactor types and behaviour of out/inN
- [x] are `outStar` and `inStar` needed?
- <s>`starInIn` and `starOutOut` call `union` even though $\alpha \notin \vec{\alpha}$?</s>
- [x] `extend`: new `out` to use `Dict.insertWith union`
- [x] `extend`: new `in` to fold `Dict.insertWith union`
- [x] delete `starInIn` and `starOutOut`

**Comment by JosephBond** [comment]
Initial implementation pass complete
