### ISSUE TITLE
Initial comparison of graph performance vs. trace approach

### ISSUE THREAD

**Issue by rolyp** [explorable-viz/fluid#642]
Performance evaluation to compare current implementation with:
- New implementation including both graph creation and slicing over graph
- Only slicing over graph

See also:
- #732

**Comment by JosephBond** [comment]
Via the very naive debugging setup I have currently implemented we can already get some data to back up our intuition regarding slicing being dramatically faster, and evaluation being slower. Moving forward, we want to tie in the benchmarking with some more infrastructure, so that we can automatically generate tables of data.

- [ ] define `BenchResult` type, for use in accumulating results over the course of the benchmarking
- [ ] thread `BenchResult` through benchmarking code
- [ ] derive a `Show` instance, so can use `BenchResult` to generate tables

**Comment by rolyp** [comment]
The following may be related:
- #731

In the test cases Chrome is running in headlless mode so it should be possible to serve files and then downloaded them e.g. for testing/benchmarking/paper building purposes.

**Comment by rolyp** [comment]
Closing this as completed. Separate tasks will deal with extracting benchmarking data in CSV format, generating figures for the paper, etc.

See also:
- #738
