### ISSUE TITLE
`fwdSlice` implementation based on De Morgan dual

### ISSUE THREAD

**Issue by rolyp** [explorable-viz/fluid#675]
For performance comparison purposes, and for testing/sanity-checking, it would be useful to have the De Morgan implementation for `fwdSlice`.

- [x] Integrate into test framework and verify equivalent to existing implementation of `fwdSlice`

**Comment by min-nguyen** [comment]
>  I think we’ll need to have a clear notion of the “inputs” and “outputs” of a graph for this to make sense. For the inputs, the sinks seem to be the appropriate notion (but we may want to avoid that composition of G and G’ as discussed the other day, otherwise the sinks will be quite numerous but mostly irrelevant). For the outputs, maybe we can consider an arbitrary set of vertices (not sure, but the formalism will need some work here). For a particular program which evalutes to G’, the sinks (if we avoid composing with G) will be a subset of  the vertices in γ, e, and for the onputs we will just consider the vertices in v.

>  Once we know the input/output vertex sets we’re dealing with, the De Morgan dual will then be based on complementation with respect to those sets. I.e. to forward slice for some subset of the inputs, take the complement, backward slice on op G to obtain a subset of the outputs, and then take the complement again.

**Comment by min-nguyen** [comment]
This has been implemented and the tests pass fine:
```haskell
fwdSliceDeMorgan :: forall g s. Graph g s => s Vertex -> g -> g
fwdSliceDeMorgan αs g' =
   bwdSlice (sinks g' `difference` αs) (op g')

...
gfwd = G.fwdSliceDeMorgan αs_in g
v𝔹 = select𝔹s vα (vertices gfwd') <#> not 
```
However,  we exceed the maximum call stack size for 4 tests. This is because usually when we backward slice, we're doing it with respect to a _handful_ of selections (on the value). Now in the de morgan dual, we're backward slicing with respect to _hundreds_ of selections (i.e. the complement of a handful of selections on the expression). So I don't know if it's realistic for this to be resolved.

**Comment by min-nguyen** [comment]
New thoughts: when we're selecting lots of sources on backward slicing, intuitively, they're going to share a lot of ancestral nodes. I wonder if this could somehow be used to address the call-stack problem. Perhaps relatedly, I wonder how a breadth-first approach compares to a depth-first for backwards slicing.

**Comment by min-nguyen** [comment]
I've done some playing around. If I understand correctly, we currently implement depth-first slicing in the snippet `(L.fromFoldable βs <> αs)`:
```haskell
bwdVertices :: forall g s. Graph g s => g -> s Vertex -> List Vertex -> WithGraph s Unit
bwdVertices _ _ Nil = pure unit
bwdVertices g' visited (α : αs) =
   if α `member` visited then bwdVertices g' visited αs
   else do
      let βs = outN g' α
      extend α βs
      bwdVertices g' (visited # insert α) (L.fromFoldable βs <> αs)
```
Breadth-first slicing can be implemented by swapping to `(αs <> L.fromFoldable βs)`. Both have the same performance, but breadth-first search results in only 3 tests (rather than 4) exceeding the max call-stack size; specifically, the `slicing/convolution/emboss` runs fine for breadth-first, but not depth-first. I've since swapped to using breadth-first.

**Comment by rolyp** [comment]
Interesting, thanks. Maybe this is a reason to switch the slicing algorithms to an explicitly tail-recursive form using `purescript-tailrec`?

**Comment by rolyp** [comment]
Added a “todo” to check that this implementation behaves the same as the existing one in the test harness. Maybe this is something we could enable with a flag (set to `False` once we’re satisfied the implementations agree).

**Comment by min-nguyen** [comment]
Interesting - the tail recursive implementation fixed the call-stack problem. This now reveals that appears the breadth-first version of bwd-slicing times out (on `convolution/edgeDetect`) , and the depth-first version is a lot more performant.
