### ISSUE TITLE
`testWithSetup` decomposition

### ISSUE THREAD

**Issue by rolyp** [explorable-viz/fluid#691]

**Comment by min-nguyen** [comment]
I've decomposed the tests for trace and graph based approaches to be more orthogonal, so that the latter doesn't depend on the output of the former.

I've made the tests as symmetric as possible for now so the graph-based test now performs desugaring/resugaring, which is obviously a bit redundant, but it makes the both of the tests more consistent.

**Comment by rolyp** [comment]
@min-nguyen This looks good, thanks!
