### ISSUE TITLE
Closures to depend on associated `fun` or `letrec` expression

### ISSUE THREAD

**Issue by min-nguyen** [explorable-viz/fluid#700]
Re: our conversation in https://github.com/explorable-viz/fluid/issues/382#issuecomment-1676382897

> I can’t right now think of a situation where a node can be created that won’t at least depend on an expression found either in the original program or in a closure reachable within the environment.

I've done some more debugging, and i've found out that it's happening at the top-level of evaluation, when `αs` in `eval γ e αs` will be initially empty, and a new address is allocated which points to that empty set.

For example, if we are evaluating a top-level expression `LetRec ρ e`, the first thing will that will be called is `closeDefs`. This will in turn create a `Closure` with a new address that points to the empty set of addresses, thus producing a new sink in the graph that is not found in the original expression.
```haskell
eval γ (LetRec ρ e) αs = do
   γ' <- closeDefs γ ρ αs
   eval (γ <+> γ') e αs

closeDefs γ ρ αs =
   flip traverse ρ \σ ->
      let ρ' = ρ `for` σ
      in V.Fun <$> (V.Closure <$> new αs <@> 
                    (γ `restrict` (fv ρ' `S.union` fv σ)) <@> ρ' <@> σ)
```
An example of a program that does this is `slicing/zeros.fld`, where evaluating `zeros` to a closure does not currently depend on anything.
```
let zeros [] = [];
    zeros (x : xs) = 0 : zeros xs
in
zeros [1, 2]
```
Let me know your thoughts on whether this should be happening or not.

**Comment by rolyp** [comment]
Yep, good point. Closures created by the lambda rule also only depend on the ambient `αs`, which can be empty. 

Because this is the _only_ case where values don’t depend somehow on expressions, I’m tempted to introduce a distinction between the previous semantics and the new, by introducing an edge between closures and either the lambda expression or the `letrec` expression that was responsible for their creation. We might (for as long as we have both semantics) be able to hide this distinction in the prettyprinter, by ignoring the annotations on `Lambda` and `LetRec` expressions, i.e. preserve the (apparent) equivalence between the two semantics for testing purposes but internally having a stronger link between values and expressions.

**Comment by JosephBond** [comment]
Won't give us the properties we want, so closing this issue.

**Comment by rolyp** [comment]
To clarify after yesterday’s discussion. I think I was wrong to identify (as an example of a sink not in $\gamma, e$) a function which doesn’t consume its argument (because it matches it with a variable eliminator) but that produces some output which is subsequently depended on. That won’t be a sink because the output will depend on the closure itself which (if we made the proposed change) would link to a source expression.

However, it nevertheless remains (I think) that sinks are not in general contained in $\gamma, e$, because $\gamma$ may contain values derived from expression fragments which have already been processed by evaluation. So those paths will lead out of $\gamma, e$.

Going to reopen as Proposed though because we may still want to do this anyway, or something similar.
