### ISSUE TITLE
Consolidate error handling strategy

### ISSUE THREAD

**Issue by rolyp** [explorable-viz/fluid#721]
Currently
- We use both `Either String` (`MayFail`) and `ExceptT String` (`MayFailT`); although the latter does convert to the former when exiting the monad, we should probably migrate direct use of `Either String` to `Except String` and consolidate the naming. 
- We rely too much on forcing `Either String a` to `a` using `successful`, especially in `Aff` code, rather than allowing the error to propagate. We should map this to an exception or some other kind of failure supported by `Aff`. There are times however where `successful` is appropriate (because an invariant guarantees that the error condition can never arise), so these will have to be evaluated on a case-by-case basis.

**Comment by rolyp** [comment]
@min-nguyen Btw, `orElse` (by design) works well with the “pipe” operator (i.e. `|` in Bash, `|>` in F#, `&` in Haskell, or in PureScript, `#`). Then you can write:

```purescript
lookup x γ # orElse ("variable " <> x <> " not found")
```

**Comment by min-nguyen** [comment]
Note: The changes have resulted in a notable performance decrease (15s to 22s on my machine in uni). We decided to keep these changes as they're more sustainable/ergonomic for error handling (`eval` is a lot cleaner now), and because the performance hits are across the entire implementation rather than being specific to graph slicing (and it might even be the case they're decreasing performance on things that don't really matter e.g. the old trace-based `eval`). In other words, it won't impact how we compare performance within our own system. It might be a different story if we wanted to compare performance with other languages.
