### ISSUE TITLE
drawFiles function to directly draw files in CodeMirror buffer

### ISSUE THREAD

**Issue by JosephBond** [explorable-viz/fluid#740]
For convolution.fld, and, eventually, Dataset.fld, we need a way to draw fluid files in codemirror buffers that aren't directly tied to a figure. To do that, we'll need to add a function called `drawFile :: EditorView -> Folder -> File -> Effect Unit` (may be able to package the folder/file together, or could load the string before calling drawFile), which will take an editorview, and populate it with code from the specified file. Then in `app/Main.purs`, we need a function which, given a collection of `File`'s, produces appropriate `EditorView`'s for each file, and then sequentially passes them all to `drawFile`

**Comment by rolyp** [comment]
@harleengulati03 I think it is a timing-related error – not because the PureScript code is doing anything in the wrong order, but because the underlying `d3.js` call to `select` may be running too early to see the `div` with the required id. (For example, when writing a regular JS/HTML app using d3, [just reordering the relative position](https://stackoverflow.com/questions/16823757/d3-selectelement-not-working-when-code-above-the-html-element) of the `div` with the `script` tag that loads some JS code doing the `select` may cause this problem.)

It’s [recommended](https://stackoverflow.com/questions/2451417/whats-pros-and-cons-putting-javascript-in-head-and-putting-just-before-the-bod) to put any JS scripts in the `body` (at the bottom) rather than the `head` of the HTML file to avoid these sorts of loading-related timing issues. And indeed, if I move `<script src="app.js"></script>` (the JS script that contains the compiled PureScript code) from the `head` to the `body` in `index.html`, then the problem seems to go away.
