### ISSUE TITLE
Discrepancy between bwd dual implementations

### ISSUE THREAD

**Issue by JosephBond** [explorable-viz/fluid#818]
- [x] #890
- [x] #893
- [x] `bwdSlice`: `extend α βs` step only happens when βs is non-empty, but that will exclude sinks
- <s>`toEdgeList` to return set of inputs?</s>
- <s>`.dot` output to omit isolated vertices?</s>
- [x] #908
- [x] Identity failing tests (`nub`, `slicing/filter`, `mergeSort`, `range`, `slicing/matrix-update`, `graphics/line-chart`)
- [x] Verify whether there are outputs which aren’t sources (yes for all 6, plus another 12 cases)
- [x] MWE for outputs which aren’t sources; check causes test failure (`output-not-source.fld`)
- [x] Experiment with checking inputs/outputs as sinks/sources in `fwdSlice`/`bwdSlice`
- [x] Restrict arguments to `bwdSlice` to `sources g`

See also:
- explorable-viz/graphical-slicing#218
- #896 
- #897
- #906
- #907

***
Currently, I’m not sure our definition of the bwd-Dual via the double complementing is correct. The intuitive definition doesn’t compute the same “dual-slice” as the version implemented via forward slicing on the opposite graph.

Fix `g’ = G.bwdSliceDualAsFwdOp αs g` and `g’’ = G.bwdSliceDual vα αs g`

If we implement the backward dual as follows:
`bwdSliceDual vα αs0 g0 = bwdSlice (vertices vα `difference` αs0) g0`, then:
`(prettyP $ select𝔹s eα (sinks g’)) != (prettyP $ (select𝔹s eα (sinks g’’) <#> not))`

However, the above ARE equal if we change the definition:
`bwdSliceDual _ αs0 g0 = bwdSlice (vertices g0 `difference` αs0) g0`

Which feels incorrect. This behaviour can be seen in the benchmarking branch.

**Comment by rolyp** [comment]
There is a clear relationship to explorable-viz/graphical-slicing#218: sinks that are not treated as inputs will invalidate the De Morgan implementation of fwd slicing, and presumably there is something analogous for sources that are not treated as outputs and the De Morgan implementation of bwd slicing.

<img src="https://github.com/explorable-viz/fluid/assets/121074/8d0b48b5-db29-454f-9ec7-a4e4435981a7" width="400">

**Comment by rolyp** [comment]
And indeed, similar problem for bwd dual as fwd on opposite:

<img src="https://github.com/explorable-viz/fluid/assets/121074/106694ff-a0f6-4344-89f2-947992b8b7bc" width="400">

**Comment by rolyp** [comment]
So it seems every source needs to be an output for things to work properly. But does every output need to be a source? The following shows that outputs that aren’t sources are potentially problematic too, but I think this can be addressed by requiring output slices (i.e. subsets of the outputs) to be “closed” with respect to the dependency relation, i.e. if x is in the output slice then so are any other outputs that x depends on.

<img src="https://github.com/explorable-viz/fluid/assets/121074/096659c7-7a59-4e36-9406-9c04b7239c50" width="400">

**Comment by JosephBond** [comment]
Does this imply that we need to do a tiny bit of preprocessing on the output slice for backward slicing? (IE to preselect some extra input before we slice? Or is it only relevant in the dual, ie the selection we complement with respect to must downward close itself?

**Comment by rolyp** [comment]
Yes I think we’ll need to “automatically” ensure slices are closed in the appropriate way. (In this case it doesn’t seem unreasonable because you can think of bwd slicing as a kind of “selection” that traverses dependency edges anyway, and so we just need to make sure that the initial slice already has any other dependent output nodes included.)

(For the maths to make sense I think this will be the case for all output slices, not just for the De Morgan dual.)

**Comment by rolyp** [comment]
The following shows that output slices need to be “upward closed” as well. If α is in the output slice and some other output which is not in the slice depends on it, then α will be “pulled in” when computing the complement fwd slice. Any additional input included into the fwd slice as a consequence will then be excluded from the bwd slice:

<img src="https://github.com/explorable-viz/fluid/assets/121074/9b44f6dc-6482-4bd6-a810-79b7cf9a2e90" width="400">

Combined with the previous observation, I think this means that output slices are the _components_ (maximal connected subgraphs) of the set of outputs considered as a subgraph of $G$:

<img src="https://github.com/explorable-viz/fluid/assets/121074/d1fda550-e15c-4e28-9b55-e16508a26b6e" width="300">

At face value this seems reasonable. The powerset of the set of components would then be the Boolean algebra on the output.

**Comment by JosephBond** [comment]
That does seem reasonable. It suggests a slight coarsening of selections, but I agree that it doesn't seem inherently problematic. As an aside, it also means we get some more nice diagrams for the paper, and more discussion in the Graph section

**Comment by rolyp** [comment]
One question is how this related to the algorithms, which don’t deal explicitly with these components. In some sense that should be ok (it’s just a constraint/interpretation on the input/output to the algorithms), however I’m wondering about fwd slicing, what happens if it only produces a proper part of a component? I.e. how do we interpret fwd as the upper adjoint whose codomain now is a set of components? If you don’t have all the elements of a component then I don’t think you can have the component, i.e. an invocation of fwd that only produced a proper part of a component would actually have $\bot$ (empty set of components) as its output. So the “coarsening” of selections would also have to happen at the point at which we interpret the output of fwd as the image of an input selection in the upper adjoint.

(Refer back to the diagram above, imagine selecting the circled node on the input and then fwd slicing. That suffices for α, but α is needed by another output, so actually the output selection would be empty.)

**Comment by rolyp** [comment]
As we said at the beginning, every sink needs to be an input. As we did with outputs, we can also ask the question of whether every input needs to be a sink. I think the analysis is basically the same as for outputs and bwd slicing:

<img src="https://github.com/explorable-viz/fluid/assets/121074/a91b1ab2-98e4-4bb0-accd-53d86a25bc08" width="500">

I think this means that, given $G$, we can slice with any subset of $V(G)$ as the inputs and any subset of $V(G)$ as the outputs, as long as the input and output Boolean algebras are given by the set of _components_ of the induced subgraphs of the respective sets. I don’t think we have to restrict $G$ somehow, we just need to intersect the resulting slice $G’$ with the original input/output components. (Although maybe need to check the case where the inputs and outputs overlap.)

**Comment by rolyp** [comment]
Ok (and hopefully I’m nearing the end of this investigation) there is one other sense in which inputs and outputs may not be sinks/sources as appropriate: if they have dependees/dependents which lie not within the input/output sets but “beyond” them:

<img src="https://github.com/explorable-viz/fluid/assets/121074/0b6f536c-6674-46d5-9088-3a7ee2194761" width="600">

I think this is ok too. We should still be able to slice using the underlying $G$, we just need to be careful to intersect the resulting slice $G$’ with the relevant set of inputs/outputs.

**Comment by rolyp** [comment]
Regardless of explorable-viz/graphical-slicing#218, I’m not convinced that the scope of the graph that we invert is actually correct – we flip the whole graph, but really a `graphGC` should only relate to the subgraph built during that evaluation.

**Comment by rolyp** [comment]
Ok, the new debug infrastructure is super-helpful, in a few seconds I can produce the following (the table is mine, the values in the table are auto-generated):

`G-BwdDlFwdOp`             |  `G-BwdDlCmp`
:-------------------------|:-------------------------
`fwdSlice`             |  `bwdSlice`
$g^{op}$             |  $g$
`input: {}` | `input: {332}`
![graphviz (1)](https://github.com/explorable-viz/fluid/assets/121074/970d1f32-666c-4165-adc4-84ee31fc8978) |  ![graphviz](https://github.com/explorable-viz/fluid/assets/121074/115f556d-b62b-4631-a048-7b5b0329c207)

Problems:
- [x] underlying operation on the left should be `fwdSlice`

**Comment by rolyp** [comment]
With new debugging infrastructure and recent consolidation, we currently have:
- Bwd duals mostly disagree. Seems likely to be the analogue of the sinks/inputs issue, but for sources/outputs; in the graph $g$ above, for example, there are multiple sources, but (I think) the output only consists of vertex `332`. I don’t think we can require that every source is an output (it’s fine to make a value and then throw it away), so we may need to rethink a few assumptions here.
- Fwd duals agree except in graphics cases (probably for same reason as #896). It would be useful to be able to print the difference between two selections, i.e. lift relative complement pointwise to selectable values of the same shape.
- Naive fwd agrees with direct fwd in all except graphics cases too. This test runs fwd with the result of bwd, which for the graphics tests will be the empty selection; so actually it would seem that the two fwd implementations differ even on empty input (where the fwd slice should be empty). See #896.

**Comment by rolyp** [comment]
Fwd duals now agree after fix to #896.

**Comment by rolyp** [comment]
As surmised, even with all the recent changes/fixes to graph slicing, the problem of “outputs which aren’t sources” is still present, and seems to the remaining source of discrepancy between `BwdDualFwdOp` and `BwdDualCmp`. These arise when an value is both returned and used. This happens in about 12 test cases, and it’s problematic for the equivalence of these two operations in 6 of those. It affects the behaviour of `BwdDualFwdOp` in the `output-not-source.fld` MWE: 

`let x = 3 in (x, x < 5)`

because `BwdDualFwdOp` with respect to the left component of the output will discard the `3` in the program, even though it is still needed for the second component of the output.

For now, we simply _exclude_ any vertices which are not sources from the initial vertices passed to `bwdSlice`. For all test cases other than `output-not-source.fld`, this restores the equivalence of `BwdDualFwdOp` and `BwdDualCmp`. 

Potentially this will produce incorrect behaviour in the UI. For example, in `output-not-source.fld`, attempting to select `3` will discard that selection and end up backward-slicing using the empty selection, causing the test will fail because it disagrees with the trace-based slicing. So instead we select the second component of the pair and retain the test as a piece of documentation. 

I think this is best revisited when we come back to the graph semantics, where it seems likely that edges will represent evaluation steps, and vertices may no longer be values directly but may instead be labelled with values. Closing as completed for now.
